---
  - name: Set-up ELK VM
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:

      - name: Install docker.io
        apt:
          update_cache: yes
          force_apt_get: yes
          name: docker.io
          state: present

      - name: Install python3-pip
        apt:
          name: python3-pip
          force_apt_get: yes
          state: present

      - name: Install docker
        pip:
          name: docker
          state: present

      - name: Increase VM memory
        ansible.posix.sysctl:
          name: vm.max_map_count
          value: '262144'
          state: present
          reload: yes


      - name: Pull the container image
        docker_image:
          name: sebp/elk:761
          source: pull

      - name: Create ELK container
        docker_container:
          name: elk
          image: sebp/elk:761
          restart: yes
          restart_policy: always
          published_ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044

      - name: Enable docker service
        systemd:
          name: docker
          enabled: yes
