---
- name: Install and launch metricbeat
  hosts: webservers
  become: true
  tasks:

    - name: Download metricbeat .deb package
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: Install metricbeat
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    - name: Copy config file to metricbeat.yml
      copy:
        src: /etc/ansible/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and config docker mod for metric beat
      command: metricbeat modules enable docker

    - name: metric beat setup
      command: metricbeat setup -e

    - name: metric beat start
      command: service metricbeat start

    - name: Make sure metric beat is runs on boot
      systemd:
        enabled: yes
        name: metricbeat
